apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-sync-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-scheduler
            image: job-scheduler:latest
            imagePullPolicy: Never
            args:
            - "--job.name=dataSyncScheduler"
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            resources:
              requests:
                memory: "500Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
          restartPolicy: Never
           
